### ISSUE TITLE
Cannot reach API

### ISSUE THREAD

**Issue by fitwist** [JacobCoffee/litestar-template#6]
Steps:

- forked repo
- added locally working get request
- deployed on Railway ('Uvicorn running on http://0.0.0.0:8000/ (Press CTRL+C to quit)')

Now I cannot reach API via any of the requests:
```
GET: https://litestar-gpt-support-production.up.railway.app/
Authorization: bearer {token}
```

or 
```
https://litestar-gpt-support-production.up.railway.app/
http://litestar-gpt-support-production.up.railway.app/
http://litestar-gpt-support-production.up.railway.app:8000/ (port has been specified)

```

The requests' attempts take up to 60 seconds and then 'request timed out'. cURL doesn't help either.
Local deploy works correctly. What can I do to fix this issue?

**Comment by JacobCoffee** [comment]
Hi, sorry I missed this - I will take a look tomorrow

**Comment by JacobCoffee** [comment]
It looks like everything is working again.
2 days again i checked and mine also wasn't working, but today yours mine and another persons is working.

Maybe railway was down?

let us know if you still have issues
